### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: Microsoft.Quantum.Canon
summary: >-
  Gera a composição de duas funções.


  Ou seja, dadas duas funções $f $ e $g $, retorna uma nova função representando $f \circ g $.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: A segunda função a ser aplicada.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: A primeira função a ser aplicada.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: Uma nova função $h $ de modo que para todas as entradas $x $, $f (g (x)) = h (x) $.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: O tipo de entrada da primeira função a ser aplicada.
- uid: "'U"
  summary: O tipo de saída da primeira função a ser aplicada e o tipo de entrada da segunda função a ser aplicada.
- uid: "'V"
  summary: O tipo de saída da segunda função a ser aplicada.
ms.openlocfilehash: 69fbd6a4fafbc61a63e41257b7100303fd48d4d4
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 10/31/2019
ms.locfileid: "73223064"
